import './globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  console.log("Montando layout principal");
  return (
    <html lang="en">
      <body className="bg-gray-100 min-h-screen text-gray-800">
        <div className="bg-white shadow-md">
          <nav
            className="max-w-4xl mx-auto p-4 flex justify-between items-center"
            aria-label="Menu Principal"
          >
            <h2 className="text-xl font-bold text-blue-600">Menu Principal</h2>
            <ul className="flex gap-4">
              <li>
                <a
                  href="/"
                  className="text-gray-700 hover:text-blue-500 transition-colors"
                >
                  Home
                </a>
              </li>
              <li>
                <a
                  href="/novarota"
                  className="text-gray-700 hover:text-blue-500 transition-colors"
                >
                  Nova Rota
                </a>
              </li>
            </ul>
          </nav>
        </div>
        <main className="max-w-4xl mx-auto p-6 bg-white shadow-md rounded-lg">
          {children}
        </main>
      </body>
    </html>
  );
}
